env:
  global:
  - PLAT=x86_64
  - BUILD_REF=apache-arrow-0.8.0
language: python
python: 3.5
sudo: required
dist: trusty
services:
- docker
matrix:
  exclude:
  - python: 3.5
  include:
  - os: osx
    language: objective-c
    env:
    - MB_PYTHON_VERSION=2.7
    - NP_BUILD_DEP=1.10.1
    - NP_TEST_DEP=1.10.1
    - PANDAS_DEP="0.20.3"
  - os: osx
    language: objective-c
    env:
    - MB_PYTHON_VERSION=3.5
    - NP_BUILD_DEP="1.10.1"
    - NP_TEST_DEP="1.10.1"
    - PANDAS_DEP="0.20.3"
  - os: osx
    language: objective-c
    env:
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP="1.11.3"
    - NP_TEST_DEP="1.11.3"
    - PANDAS_DEP="0.20.3"
  - language: cpp
    os: linux
    before_script:
    - docker pull quay.io/xhochy/arrow_manylinux1_x86_64_base:latest
    before_install:
    install:
    script:
    - mkdir -p dist
    - pushd arrow/python/manylinux1
    - git clone ../../ arrow
    - docker build -t arrow-base-x86_64 -f Dockerfile-x86_64 .
    - docker run --shm-size=2g --rm -e PYARROW_PARALLEL=3 -v $PWD:/io arrow-base-x86_64
      /io/build_arrow.sh
    - popd
    - sudo mv arrow/python/manylinux1/dist/* dist/
  - language: ruby
    os: linux
    before_script:
    before_install:
    install:
    script:
    - (cd cpp-linux && travis_wait 40 rake apt:build APT_TARGETS=debian-stretch,ubuntu-trusty,ubuntu-xenial PARALLEL=yes DEBUG=no)
    deploy:
      provider: bintray
      file: cpp-linux/apt/descriptor.json
      user: kou
      on:
        all_branches: true
      key:
        secure: "XXRJFBIOGS9urF047KcGlCqnMwKWa/EhW1Q2A3JGDd7Au+NHd99Rl/iRbtd44xVnfhosKGEH9mBGrqIZb/Tfn3RTtSi/KvN2RIoWmdsc3Kxk1eKd6O9kCLo4Y1GqboK8JVIHD4OYiyoVoFmnYLuinfdtrZrME5aU4pENnvwR3E0qvjhnhfwRG/Mtb93ePAqzih95gT7S0VWlsBV3FPa21aY7ctFteUP+DdqXZX1BmUnJB6cBxUGjpL8Bu8O/mt3l3yIrT9UkWM1g75l7zrP354x5+AMbHWBv7yGFa+JvbB+LXkrE2dV6j3Upf6ChnQKoTKv5Ur5LJBbCHyRieW3/uE/h47IR3c/3mRnhoSIl4QX7UoQkvTwHSE1Xpry3I2jE0WVHmq9NqT4iaxIv5oga+3I/W6h8brV3yCYfVUi1F90aRlnZHsCDmtAqzW1u9s1xqkO4z4/dennI0gniEn4kWfx0I7aCQQI/XmDri/33uTINprwBB5eHt6a7WGysrcO6Mv5I8EFEAJ5vkx2mDVw+rDFC7/R8YNA77PcJABlF7G/ZajcHqPnN5uyJC+P2m6JyHO+kTHemjW8pgf5vKvdNzdTN1AVFSO9Mv4O3NPyaADRl9DCCcqAk2LwL+SYqCVvIXu98Mb6uEoSOb+ZnpvseyydxNB6DtQSVtVUNdis5Ibw="
  - language: ruby
    os: linux
    before_script:
    before_install:
    install:
    script:
    - (cd cpp-linux && travis_wait 40 rake apt:build APT_TARGETS=ubuntu-zesty,ubuntu-artful PARALLEL=yes DEBUG=no)
    deploy:
      provider: bintray
      file: cpp-linux/apt/descriptor.json
      user: kou
      on:
        all_branches: true
      key:
        secure: "XXRJFBIOGS9urF047KcGlCqnMwKWa/EhW1Q2A3JGDd7Au+NHd99Rl/iRbtd44xVnfhosKGEH9mBGrqIZb/Tfn3RTtSi/KvN2RIoWmdsc3Kxk1eKd6O9kCLo4Y1GqboK8JVIHD4OYiyoVoFmnYLuinfdtrZrME5aU4pENnvwR3E0qvjhnhfwRG/Mtb93ePAqzih95gT7S0VWlsBV3FPa21aY7ctFteUP+DdqXZX1BmUnJB6cBxUGjpL8Bu8O/mt3l3yIrT9UkWM1g75l7zrP354x5+AMbHWBv7yGFa+JvbB+LXkrE2dV6j3Upf6ChnQKoTKv5Ur5LJBbCHyRieW3/uE/h47IR3c/3mRnhoSIl4QX7UoQkvTwHSE1Xpry3I2jE0WVHmq9NqT4iaxIv5oga+3I/W6h8brV3yCYfVUi1F90aRlnZHsCDmtAqzW1u9s1xqkO4z4/dennI0gniEn4kWfx0I7aCQQI/XmDri/33uTINprwBB5eHt6a7WGysrcO6Mv5I8EFEAJ5vkx2mDVw+rDFC7/R8YNA77PcJABlF7G/ZajcHqPnN5uyJC+P2m6JyHO+kTHemjW8pgf5vKvdNzdTN1AVFSO9Mv4O3NPyaADRl9DCCcqAk2LwL+SYqCVvIXu98Mb6uEoSOb+ZnpvseyydxNB6DtQSVtVUNdis5Ibw="
  - language: ruby
    os: linux
    before_script:
    before_install:
    install:
    script:
    - (cd cpp-linux && rake yum:build PARALLEL=yes DEBUG=no)
    deploy:
      provider: bintray
      file: cpp-linux/yum/descriptor.json
      user: kou
      on:
        all_branches: true
      key:
        secure: "XXRJFBIOGS9urF047KcGlCqnMwKWa/EhW1Q2A3JGDd7Au+NHd99Rl/iRbtd44xVnfhosKGEH9mBGrqIZb/Tfn3RTtSi/KvN2RIoWmdsc3Kxk1eKd6O9kCLo4Y1GqboK8JVIHD4OYiyoVoFmnYLuinfdtrZrME5aU4pENnvwR3E0qvjhnhfwRG/Mtb93ePAqzih95gT7S0VWlsBV3FPa21aY7ctFteUP+DdqXZX1BmUnJB6cBxUGjpL8Bu8O/mt3l3yIrT9UkWM1g75l7zrP354x5+AMbHWBv7yGFa+JvbB+LXkrE2dV6j3Upf6ChnQKoTKv5Ur5LJBbCHyRieW3/uE/h47IR3c/3mRnhoSIl4QX7UoQkvTwHSE1Xpry3I2jE0WVHmq9NqT4iaxIv5oga+3I/W6h8brV3yCYfVUi1F90aRlnZHsCDmtAqzW1u9s1xqkO4z4/dennI0gniEn4kWfx0I7aCQQI/XmDri/33uTINprwBB5eHt6a7WGysrcO6Mv5I8EFEAJ5vkx2mDVw+rDFC7/R8YNA77PcJABlF7G/ZajcHqPnN5uyJC+P2m6JyHO+kTHemjW8pgf5vKvdNzdTN1AVFSO9Mv4O3NPyaADRl9DCCcqAk2LwL+SYqCVvIXu98Mb6uEoSOb+ZnpvseyydxNB6DtQSVtVUNdis5Ibw="
before_install:
- brew uninstall boost
- brew update
- brew upgrade cmake
- BUILD_DEPENDS="numpy==$NP_BUILD_DEP six cython"
- TEST_DEPENDS="numpy==$NP_TEST_DEP six pandas==$PANDAS_DEP"
- mkdir -p dist
- pushd python-macos
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
- popd
install:
- clean_code arrow $BUILD_REF
- build_wheel arrow $PLAT
- mv arrow/python/dist/* dist/
script:
- echo "SCRIPT"
- pwd
after_success:
- echo "After success"
- pwd
deploy:
  provider: bintray
  file: descriptor.json
  user: bryancutler
  on:
    all_branches: true
  key:
    secure: "A8hx74dDKMLdlrCq6wz9scXB3OruyH9yRG77lJQ2gcVuGGAw38Ly+ez8EoDQNlcppCOF2PWNVTPidrxE60VY2vnPh1KbGxW/nbe3xCx+LGygbegB+o61tVQEKoYf4ccaLZFQgL+39znv0fI5xaUp92JczVloJnLdjh/NUXsUa6rQ1LjHLRrYW+XJjEi9TAL1Ix/oOjYReE2T4AYN3tMcQHPeFH4eCwQ3AU7PhMx6yJJw7V2GUi77HvZJndcEQRrBwJBPp/BWGGqvJA9UdEZIfW7OpKb4jTw9m/I2Tb/9iYIDKEOmnECWAuT4eai407y/ZniT2Ffj1dMgfUj6FxNtjifvilZ5qfC4h1uWX2ZeEOB8wyvLXE0ZHJdwO457aRriVWi7wtWuiba9A080WpfNoo2A+3Ui+IfufAeSUfYcZP1ZfAe2Cgt4PBS0trvQ+59naRUCeYEGTqBMegyDT4B6GkZ6iieVV9c/cyHtJZNsWqBhUtY0iN8HK+X80z8bhdsBO9NK50314CJ99PTtiMpIxihstf9w1x4KCSrTCnc1KUNBplxpzLXuANyPlEsL1c9qetzYCgdrAG8p5nD2EKI5brM3dmiNeA4UC2GDj702iRhhazesOETmLADZdSR+RKj7pOXnNjkp+LoU4EqfTI/0vixMjEX4TPstRHA8jrxv/IE="
